= Commands used in Chapter 12

== Create an interactive session with ksqlDB

docker exec -it ksqldb-cli ksql http://ksqldb-server:8088

== Create an interactive session with ksqlDB

CREATE STREAM hunterLocations (treasureId VARCHAR, latitude DOUBLE, longitude DOUBLE)
  WITH (kafka_topic='loc', key='treasureId', value_format='json', partitions=1);

== Create an interactive session with ksqlDB

SELECT * FROM hunterLocations
  WHERE GEO_DISTANCE(latitude, longitude, 43.6693, 92.9747, 'mi') \<= 1 EMIT CHANGES;

== New stream events on locations

INSERT INTO hunterLocations (treasureId, latitude, longitude) VALUES ('team1', 53.6693, 93.9747);
INSERT INTO hunterLocations (treasureId, latitude, longitude) VALUES ('team2', 43.6694, 92.9847);

== Start ksqlDB in headless mode

./bin/ksql-server-start ./etc/ksql/ksql-server.properties \
--queries-file /ksql.sql

== running a new version of Streams app

. start Confluent Platform 
+

`confluent local services ksql-server start`
. Build and run an app
+

`./gradlew run`

. produce some data using `kafka-avro-console-producer`
+

[source,shell script]
.test-data
----
kafka-avro-console-producer --topic transaction-request --bootstrap-server localhost:9092 --property value.schema="$(< src/main/avro/transaction.avsc)"
      
{"guid":"220acb8b-9353-4f63-950b-02e030902b2a","account":"1","amount":"'\u0010","type":"DEPOSIT","currency":"CAD","country":"CA"}
{"guid":"987ec7c5-878c-438a-a33b-d48c142479dd","account":"1","amount":"N ","type":"DEPOSIT","currency":"CAD","country":"CA"}
{"guid":"a7b99a64-851f-4886-8505-b99d2f74851c","account":"1","amount":"u0","type":"DEPOSIT","currency":"CAD","country":"CA"}
{"guid":"0625d34b-e523-41f6-b015-4a3994684cb1","account":"1","amount":"u0","type":"WITHDRAW","currency":"CAD","country":"CA"}
{"guid":"af92438d-ce6e-4c90-b957-75846f83183a","account":"1","amount":"\u0001 ","type":"WITHDRAW","currency":"CAD","country":"CA"}
{"guid":"a2124811-de5c-4dca-8a85-912d098ea72f","account":"2","amount":"'\u0010","type":"DEPOSIT","currency":"USD","country":"USA"}
{"guid":"78fcb5f2-64f7-4c15-8891-29caddc9bb90","account":"2","amount":"\u0013","type":"DEPOSIT","currency":"USD","country":"USA"}
{"guid":"7bb790ec-96b9-47f6-b2b2-ebf36cb41da7","account":"2","amount":"u0","type":"DEPOSIT","currency":"USD","country":"USA"}
----

. consume result from 
+

[source,shell script]
.consume
----
kafka-avro-console-consumer --bootstrap-server localhost:9092 --from-beginning --topic transaction-failed --property schema.registry.url=http://localhost:8081 #<1>

{"transaction":{"guid":"af92438d-ce6e-4c90-b957-75846f83183a","account":"1","amount":"\u0001 ","type":"WITHDRAW","currency":"CAD","country":"CA"},"funds":{"account":"1","balance":"u0"},"success":false,"errorType":{"org.kafkainaction.ErrorType":"INSUFFICIENT_FUNDS"}}

kafka-avro-console-consumer --bootstrap-server localhost:9092 --from-beginning --topic transaction-success --property schema.registry.url=http://localhost:8081 #<2>

{"transaction":{"guid":"220acb8b-9353-4f63-950b-02e030902b2a","account":"1","amount":"'\u0010","type":"DEPOSIT","currency":"CAD","country":"CA"},"funds":{"account":"1","balance":"'\u0010"},"success":true,"errorType":null}
{"transaction":{"guid":"987ec7c5-878c-438a-a33b-d48c142479dd","account":"1","amount":"N ","type":"DEPOSIT","currency":"CAD","country":"CA"},"funds":{"account":"1","balance":"u0"},"success":true,"errorType":null}
{"transaction":{"guid":"a7b99a64-851f-4886-8505-b99d2f74851c","account":"1","amount":"u0","type":"DEPOSIT","currency":"CAD","country":"CA"},"funds":{"account":"1","balance":"\u0000ê`"},"success":true,"errorType":null}
{"transaction":{"guid":"0625d34b-e523-41f6-b015-4a3994684cb1","account":"1","amount":"u0","type":"WITHDRAW","currency":"CAD","country":"CA"},"funds":{"account":"1","balance":"u0"},"success":true,"errorType":null}
{"transaction":{"guid":"a2124811-de5c-4dca-8a85-912d098ea72f","account":"2","amount":"'\u0010","type":"DEPOSIT","currency":"USD","country":"USA"},"funds":{"account":"2","balance":"'\u0010"},"success":true,"errorType":null}
{"transaction":{"guid":"78fcb5f2-64f7-4c15-8891-29caddc9bb90","account":"2","amount":"\u0013","type":"DEPOSIT","currency":"USD","country":"USA"},"funds":{"account":"2","balance":":"},"success":true,"errorType":null}
{"transaction":{"guid":"7bb790ec-96b9-47f6-b2b2-ebf36cb41da7","account":"2","amount":"u0","type":"DEPOSIT","currency":"USD","country":"USA"},"funds":{"account":"2","balance":"\u0000¯È"},"success":true,"errorType":null}
----
<1> Failed transactions
<2> Successful transactions 



